name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: "Level"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - stable
          - rc
          - beta
          - alpha
      release_notes:
        description: "Release notes"
        required: true
        type: string

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17"
          otp-version: "27.0"
      - name: Restore dependencies cache
        uses: actions/cache@v4.0.2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Setup git user
        run: |
          git config --global user.name 'tfiedlerdejanze'
          git config --global user.email 'tfiedlerdejanze@users.noreply.github.com'
      - name: Write release notes
        run: echo ${{ github.event.inputs.entry }} > RELEASE.md
      - name: Install dependencies
        run: mix deps.get
      - name: Release & Publish
        run: mix expublish.${{ github.event.inputs.level }}
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
